import os
from datetime import date
from pathlib import Path

def get_gbif_columns():
    gbif_source_cols = [
        'gbifID', 'accessRights', 'bibliographicCitation', 'language', 'license', 'modified', 'publisher', 'references',
        'rightsHolder', 'type', 'institutionID', 'collectionID', 'datasetID', 'institutionCode', 'collectionCode',
        'datasetName', 'ownerInstitutionCode', 'basisOfRecord', 'informationWithheld', 'dataGeneralizations',
        'dynamicProperties', 'occurrenceID', 'catalogNumber', 'recordNumber', 'recordedBy', 'recordedByID',
        'individualCount', 'organismQuantity', 'organismQuantityType', 'sex', 'lifeStage', 'reproductiveCondition',
        'caste', 'behavior', 'vitality', 'establishmentMeans', 'degreeOfEstablishment', 'pathway',
        'georeferenceVerificationStatus', 'occurrenceStatus', 'preparations', 'disposition', 'associatedOccurrences',
        'associatedReferences', 'associatedSequences', 'associatedTaxa', 'otherCatalogNumbers', 'occurrenceRemarks',
        'organismID', 'organismName', 'organismScope', 'associatedOrganisms', 'previousIdentifications',
        'organismRemarks', 'materialEntityID', 'materialEntityRemarks', 'verbatimLabel', 'materialSampleID', 'eventID',
        'parentEventID', 'eventType', 'fieldNumber', 'eventDate', 'eventTime', 'startDayOfYear', 'endDayOfYear', 'year',
        'month', 'day', 'verbatimEventDate', 'habitat', 'samplingProtocol', 'sampleSizeValue', 'sampleSizeUnit',
        'samplingEffort', 'fieldNotes', 'eventRemarks', 'locationID', 'higherGeographyID', 'higherGeography',
        'continent', 'waterBody', 'islandGroup', 'island', 'countryCode', 'stateProvince', 'county', 'municipality',
        'locality', 'verbatimLocality', 'verbatimElevation', 'verticalDatum', 'verbatimDepth',
        'minimumDistanceAboveSurfaceInMeters', 'maximumDistanceAboveSurfaceInMeters', 'locationAccordingTo',
        'locationRemarks', 'decimalLatitude', 'decimalLongitude', 'coordinateUncertaintyInMeters',
        'coordinatePrecision', 'pointRadiusSpatialFit', 'verbatimCoordinateSystem', 'verbatimSRS', 'footprintWKT',
        'footprintSRS', 'footprintSpatialFit', 'georeferencedBy', 'georeferencedDate', 'georeferenceProtocol',
        'georeferenceSources', 'georeferenceRemarks', 'geologicalContextID', 'earliestEonOrLowestEonothem',
        'latestEonOrHighestEonothem', 'earliestEraOrLowestErathem', 'latestEraOrHighestErathem',
        'earliestPeriodOrLowestSystem', 'latestPeriodOrHighestSystem', 'earliestEpochOrLowestSeries',
        'latestEpochOrHighestSeries', 'earliestAgeOrLowestStage', 'latestAgeOrHighestStage',
        'lowestBiostratigraphicZone', 'highestBiostratigraphicZone', 'lithostratigraphicTerms', 'group', 'formation',
        'member', 'bed', 'identificationID', 'verbatimIdentification', 'identificationQualifier', 'typeStatus',
        'identifiedBy', 'identifiedByID', 'dateIdentified', 'identificationReferences',
        'identificationVerificationStatus', 'identificationRemarks', 'taxonID', 'scientificNameID',
        'acceptedNameUsageID', 'parentNameUsageID', 'originalNameUsageID', 'nameAccordingToID', 'namePublishedInID',
        'taxonConceptID', 'scientificName', 'acceptedNameUsage', 'parentNameUsage', 'originalNameUsage',
        'nameAccordingTo', 'namePublishedIn', 'namePublishedInYear', 'higherClassification', 'kingdom', 'phylum',
        'class', 'order', 'superfamily', 'family', 'subfamily', 'tribe', 'subtribe', 'genus', 'genericName', 'subgenus',
        'infragenericEpithet', 'specificEpithet', 'infraspecificEpithet', 'cultivarEpithet', 'taxonRank',
        'verbatimTaxonRank', 'vernacularName', 'nomenclaturalCode', 'taxonomicStatus', 'nomenclaturalStatus',
        'taxonRemarks', 'datasetKey', 'publishingCountry', 'lastInterpreted', 'elevation', 'elevationAccuracy', 'depth',
        'depthAccuracy', 'distanceFromCentroidInMeters', 'issue', 'mediaType', 'hasCoordinate', 'hasGeospatialIssues',
        'taxonKey', 'acceptedTaxonKey', 'kingdomKey', 'phylumKey', 'classKey', 'orderKey', 'familyKey', 'genusKey',
        'subgenusKey', 'speciesKey', 'species', 'acceptedScientificName', 'verbatimScientificName', 'typifiedName',
        'protocol', 'lastParsed', 'lastCrawled', 'repatriated', 'relativeOrganismQuantity', 'projectId', 'isSequenced',
        'gbifRegion', 'publishedByGbifRegion', 'level0Gid', 'level0Name', 'level1Gid', 'level1Name', 'level2Gid',
        'level2Name', 'level3Gid', 'level3Name', 'iucnRedListCategory'
    ]
    return gbif_source_cols

def get_occurrence_dwc_columns():
    occurrence_dwc_cols = [
        'geodeticDatum',
        'accessRights',
        'bibliographicCitation',
        'language',
        'license',
        'modified',
        'publisher',
        'references',
        'rightsHolder',
        'type',
        'institutionID',
        'collectionID',
        'datasetID',
        'institutionCode',
        'collectionCode',
        'datasetName',
        'ownerInstitutionCode',
        'basisOfRecord',
        'informationWithheld',
        'dataGeneralizations',
        'dynamicProperties',
        'occurrenceID',
        'catalogNumber',
        'recordNumber',
        'recordedBy',
        'recordedByID',
        'individualCount',
        'organismQuantity',
        'organismQuantityType',
        'sex',
        'lifeStage',
        'reproductiveCondition',
        'caste',
        'behavior',
        'vitality',
        'establishmentMeans',
        'degreeOfEstablishment',
        'pathway',
        'georeferenceVerificationStatus',
        'occurrenceStatus',
        'preparations',
        'disposition',
        'associatedOccurrences',
        'associatedReferences',
        'associatedSequences',
        'associatedTaxa',
        'otherCatalogNumbers',
        'occurrenceRemarks',
        'organismID',
        'organismName',
        'organismScope',
        'associatedOrganisms',
        'previousIdentifications',
        'organismRemarks',
        'materialEntityID',
        'materialEntityRemarks',
        'verbatimLabel',
        'materialSampleID',
        'eventID',
        'parentEventID',
        'eventType',
        'fieldNumber',
        'eventDate',
        'eventTime',
        'startDayOfYear',
        'endDayOfYear',
        'year',
        'month',
        'day',
        'verbatimEventDate',
        'habitat',
        'samplingProtocol',
        'sampleSizeValue',
        'sampleSizeUnit',
        'samplingEffort',
        'fieldNotes',
        'eventRemarks',
        'locationID',
        'higherGeographyID',
        'higherGeography',
        'continent',
        'waterBody',
        'islandGroup',
        'island',
        'countryCode',
        'stateProvince',
        'county',
        'municipality',
        'locality',
        'verbatimLocality',
        'verbatimElevation',
        'verticalDatum',
        'verbatimDepth',
        'minimumDistanceAboveSurfaceInMeters',
        'maximumDistanceAboveSurfaceInMeters',
        'locationAccordingTo',
        'locationRemarks',
        'decimalLatitude',
        'decimalLongitude',
        'coordinateUncertaintyInMeters',
        'coordinatePrecision',
        'pointRadiusSpatialFit',
        'verbatimCoordinateSystem',
        'verbatimSRS',
        'footprintWKT',
        'footprintSRS',
        'footprintSpatialFit',
        'georeferencedBy',
        'georeferencedDate',
        'georeferenceProtocol',
        'georeferenceSources',
        'georeferenceRemarks',
        'geologicalContextID',
        'earliestEonOrLowestEonothem',
        'latestEonOrHighestEonothem',
        'earliestEraOrLowestErathem',
        'latestEraOrHighestErathem',
        'earliestPeriodOrLowestSystem',
        'latestPeriodOrHighestSystem',
        'earliestEpochOrLowestSeries',
        'latestEpochOrHighestSeries',
        'earliestAgeOrLowestStage',
        'latestAgeOrHighestStage',
        'lowestBiostratigraphicZone',
        'highestBiostratigraphicZone',
        'lithostratigraphicTerms',
        'group',
        'formation',
        'member',
        'bed',
        'identificationID',
        'verbatimIdentification',
        'identificationQualifier',
        'typeStatus',
        'identifiedBy',
        'identifiedByID',
        'dateIdentified',
        'identificationReferences',
        'identificationVerificationStatus',
        'identificationRemarks',
        'taxonID',
        'scientificNameID',
        'acceptedNameUsageID',
        'parentNameUsageID',
        'originalNameUsageID',
        'nameAccordingToID',
        'namePublishedInID',
        'taxonConceptID',
        'scientificName',
        'acceptedNameUsage',
        'parentNameUsage',
        'originalNameUsage',
        'nameAccordingTo',
        'namePublishedIn',
        'namePublishedInYear',
        'higherClassification',
        'kingdom',
        'phylum',
        'class',
        'order',
        'superfamily',
        'family',
        'subfamily',
        'tribe',
        'subtribe',
        'genus',
        'genericName',
        'subgenus',
        'infragenericEpithet',
        'specificEpithet',
        'infraspecificEpithet',
        'cultivarEpithet',
        'taxonRank',
        'verbatimTaxonRank',
        'vernacularName',
        'nomenclaturalCode',
        'taxonomicStatus',
        'nomenclaturalStatus',
        'taxonRemarks',
    ]
    return occurrence_dwc_cols


# Get list of columns for verbatim.txt datafiles in gbif packages
def get_verbatim_gbif_columns():
    verbatim_cols = ['gbifID', 'accessRights', 'bibliographicCitation', 'language', 'license', 'modified', 'publisher', 'references', 'rightsHolder',
                         'type', 'institutionID', 'collectionID', 'datasetID', 'institutionCode', 'collectionCode', 'datasetName', 'ownerInstitutionCode',
                         'basisOfRecord', 'informationWithheld', 'dataGeneralizations', 'dynamicProperties', 'occurrenceID', 'catalogNumber', 'recordNumber',
                         'recordedBy', 'recordedByID', 'individualCount', 'organismQuantity', 'organismQuantityType', 'sex', 'lifeStage', 'reproductiveCondition',
                         'caste', 'behavior', 'vitality', 'establishmentMeans', 'degreeOfEstablishment', 'pathway', 'georeferenceVerificationStatus',
                         'occurrenceStatus', 'preparations', 'disposition', 'associatedMedia', 'associatedOccurrences', 'associatedReferences', 'associatedSequences',
                         'associatedTaxa', 'otherCatalogNumbers', 'occurrenceRemarks', 'organismID', 'organismName', 'organismScope', 'associatedOrganisms',
                         'previousIdentifications', 'organismRemarks', 'materialEntityID', 'materialEntityRemarks', 'verbatimLabel', 'materialSampleID',
                         'eventID', 'parentEventID', 'eventType', 'fieldNumber', 'eventDate', 'eventTime', 'startDayOfYear', 'endDayOfYear', 'year', 'month',
                         'day', 'verbatimEventDate', 'habitat', 'samplingProtocol', 'sampleSizeValue', 'sampleSizeUnit', 'samplingEffort', 'fieldNotes',
                         'eventRemarks', 'locationID', 'higherGeographyID', 'higherGeography', 'continent', 'waterBody', 'islandGroup', 'island', 'country',
                         'countryCode', 'stateProvince', 'county', 'municipality', 'locality', 'verbatimLocality', 'minimumElevationInMeters', 'maximumElevationInMeters',
                         'verbatimElevation', 'verticalDatum', 'minimumDepthInMeters', 'maximumDepthInMeters', 'verbatimDepth', 'minimumDistanceAboveSurfaceInMeters',
                         'maximumDistanceAboveSurfaceInMeters', 'locationAccordingTo', 'locationRemarks', 'decimalLatitude', 'decimalLongitude', 'geodeticDatum',
                         'coordinateUncertaintyInMeters', 'coordinatePrecision', 'pointRadiusSpatialFit', 'verbatimCoordinates', 'verbatimLatitude', 'verbatimLongitude',
                         'verbatimCoordinateSystem', 'verbatimSRS', 'footprintWKT', 'footprintSRS', 'footprintSpatialFit', 'georeferencedBy', 'georeferencedDate',
                         'georeferenceProtocol', 'georeferenceSources', 'georeferenceRemarks', 'geologicalContextID', 'earliestEonOrLowestEonothem', 'latestEonOrHighestEonothem',
                         'earliestEraOrLowestErathem', 'latestEraOrHighestErathem', 'earliestPeriodOrLowestSystem', 'latestPeriodOrHighestSystem', 'earliestEpochOrLowestSeries',
                         'latestEpochOrHighestSeries', 'earliestAgeOrLowestStage', 'latestAgeOrHighestStage', 'lowestBiostratigraphicZone', 'highestBiostratigraphicZone',
                         'lithostratigraphicTerms', 'group', 'formation', 'member', 'bed', 'identificationID', 'verbatimIdentification', 'identificationQualifier', 'typeStatus',
                         'identifiedBy', 'identifiedByID', 'dateIdentified', 'identificationReferences', 'identificationVerificationStatus', 'identificationRemarks', 'taxonID',
                         'scientificNameID', 'acceptedNameUsageID', 'parentNameUsageID', 'originalNameUsageID', 'nameAccordingToID', 'namePublishedInID', 'taxonConceptID',
                         'scientificName', 'acceptedNameUsage', 'parentNameUsage', 'originalNameUsage', 'nameAccordingTo', 'namePublishedIn', 'namePublishedInYear',
                         'higherClassification', 'kingdom', 'phylum', 'class', 'order', 'superfamily', 'family', 'subfamily', 'tribe', 'subtribe', 'genus', 'genericName',
                         'subgenus', 'infragenericEpithet', 'specificEpithet', 'infraspecificEpithet', 'cultivarEpithet', 'taxonRank', 'verbatimTaxonRank', 'scientificNameAuthorship',
                         'vernacularName', 'nomenclaturalCode', 'taxonomicStatus', 'nomenclaturalStatus', 'taxonRemarks']
    return verbatim_cols

def get_gbif_columns_dtypes():
    gbif_source_cols_dtypes = {
        'gbifID': 'int64',
        'accessRights': 'object',
        'bibliographicCitation': 'object',
        'language': 'object',
        'license': 'object',
        'modified': 'object',
        'publisher': 'object',
        'references': 'object',
        'rightsHolder': 'object',
        'type': 'object',
        'institutionID': 'object',
        'collectionID': 'object',
        'datasetID': 'object',
        'institutionCode': 'object',
        'collectionCode': 'object',
        'datasetName': 'object',
        'ownerInstitutionCode': 'object',
        'basisOfRecord': 'object',
        'informationWithheld': 'object',
        'dataGeneralizations': 'object',
        'dynamicProperties': 'object',
        'occurrenceID': 'object',
        'catalogNumber': 'object',
        'recordNumber': 'object',
        'recordedBy': 'object',
        'recordedByID': 'object',
        'individualCount': 'object',
        'organismQuantity': 'object',
        'organismQuantityType': 'object',
        'sex': 'object',
        'lifeStage': 'object',
        'reproductiveCondition': 'object',
        'caste': 'object',
        'behavior': 'object',
        'vitality': 'object',
        'establishmentMeans': 'object',
        'degreeOfEstablishment': 'object',
        'pathway': 'object',
        'georeferenceVerificationStatus': 'object',
        'occurrenceStatus': 'object',
        'preparations': 'object',
        'disposition': 'object',
        'associatedOccurrences': 'object',
        'associatedReferences': 'object',
        'associatedSequences': 'object',
        'associatedTaxa': 'object',
        'otherCatalogNumbers': 'object',
        'occurrenceRemarks': 'object',
        'organismID': 'object',
        'organismName': 'object',
        'organismScope': 'object',
        'associatedOrganisms': 'object',
        'previousIdentifications': 'object',
        'organismRemarks': 'object',
        'materialEntityID': 'object',
        'materialEntityRemarks': 'object',
        'verbatimLabel': 'object',
        'materialSampleID': 'object',
        'eventID': 'object',
        'parentEventID': 'object',
        'eventType': 'object',
        'fieldNumber': 'object',
        'eventDate': 'object',
        'eventTime': 'object',
        'startDayOfYear': 'object',
        'endDayOfYear': 'object',
        'year': 'object',
        'month': 'object',
        'day': 'object',
        'verbatimEventDate': 'object',
        'habitat': 'object',
        'samplingProtocol': 'object',
        'sampleSizeValue': 'object',
        'sampleSizeUnit': 'object',
        'samplingEffort': 'object',
        'fieldNotes': 'object',
        'eventRemarks': 'object',
        'locationID': 'object',
        'higherGeographyID': 'object',
        'higherGeography': 'object',
        'continent': 'object',
        'waterBody': 'object',
        'islandGroup': 'object',
        'island': 'object',
        'countryCode': 'object',
        'stateProvince': 'object',
        'county': 'object',
        'municipality': 'object',
        'locality': 'object',
        'verbatimLocality': 'object',
        'verbatimElevation': 'object',
        'verticalDatum': 'object',
        'verbatimDepth': 'object',
        'minimumDistanceAboveSurfaceInMeters': 'float64',
        'maximumDistanceAboveSurfaceInMeters': 'float64',
        'locationAccordingTo': 'object',
        'locationRemarks': 'object',
        'decimalLatitude': 'float64',
        'decimalLongitude': 'float64',
        'coordinateUncertaintyInMeters': 'float64',
        'coordinatePrecision': 'object',
        'pointRadiusSpatialFit': 'object',
        'verbatimCoordinateSystem': 'object',
        'verbatimSRS': 'object',
        'footprintWKT': 'object',
        'footprintSRS': 'object',
        'footprintSpatialFit': 'object',
        'georeferencedBy': 'object',
        'georeferencedDate': 'object',
        'georeferenceProtocol': 'object',
        'georeferenceSources': 'object',
        'georeferenceRemarks': 'object',
        'geologicalContextID': 'object',
        'earliestEonOrLowestEonothem': 'object',
        'latestEonOrHighestEonothem': 'object',
        'earliestEraOrLowestErathem': 'object',
        'latestEraOrHighestErathem': 'object',
        'earliestPeriodOrLowestSystem': 'object',
        'latestPeriodOrHighestSystem': 'object',
        'earliestEpochOrLowestSeries': 'object',
        'latestEpochOrHighestSeries': 'object',
        'earliestAgeOrLowestStage': 'object',
        'latestAgeOrHighestStage': 'object',
        'lowestBiostratigraphicZone': 'object',
        'highestBiostratigraphicZone': 'object',
        'lithostratigraphicTerms': 'object',
        'group': 'object',
        'formation': 'object',
        'member': 'object',
        'bed': 'object',
        'identificationID': 'object',
        'verbatimIdentification': 'object',
        'identificationQualifier': 'object',
        'typeStatus': 'object',
        'identifiedBy': 'object',
        'identifiedByID': 'object',
        'dateIdentified': 'object',
        'identificationReferences': 'object',
        'identificationVerificationStatus': 'object',
        'identificationRemarks': 'object',
        'taxonID': 'object',
        'scientificNameID': 'object',
        'acceptedNameUsageID': 'object',
        'parentNameUsageID': 'object',
        'originalNameUsageID': 'object',
        'nameAccordingToID': 'object',
        'namePublishedInID': 'object',
        'taxonConceptID': 'object',
        'scientificName': 'object',
        'acceptedNameUsage': 'object',
        'parentNameUsage': 'object',
        'originalNameUsage': 'object',
        'nameAccordingTo': 'object',
        'namePublishedIn': 'object',
        'namePublishedInYear': 'object',
        'higherClassification': 'object',
        'kingdom': 'object',
        'phylum': 'object',
        'class': 'object',
        'order': 'object',
        'superfamily': 'object',
        'family': 'object',
        'subfamily': 'object',
        'tribe': 'object',
        'subtribe': 'object',
        'genus': 'object',
        'genericName': 'object',
        'subgenus': 'object',
        'infragenericEpithet': 'object',
        'specificEpithet': 'object',
        'infraspecificEpithet': 'object',
        'cultivarEpithet': 'object',
        'taxonRank': 'object',
        'verbatimTaxonRank': 'object',
        'vernacularName': 'object',
        'nomenclaturalCode': 'object',
        'taxonomicStatus': 'object',
        'nomenclaturalStatus': 'object',
        'taxonRemarks': 'object',
        'datasetKey': 'object',
        'publishingCountry': 'object',
        'lastInterpreted': 'object',
        'elevation': 'object',
        'elevationAccuracy': 'object',
        'depth': 'object',
        'depthAccuracy': 'object',
        'distanceFromCentroidInMeters': 'object',
        'issue': 'object',
        'mediaType': 'object',
        'hasCoordinate': 'object',
        'hasGeospatialIssues': 'object',
        'taxonKey': 'object',
        'acceptedTaxonKey': 'object',
        'kingdomKey': 'object',
        'phylumKey': 'object',
        'classKey': 'object',
        'orderKey': 'object',
        'familyKey': 'object',
        'genusKey': 'object',
        'subgenusKey': 'object',
        'speciesKey': 'object',
        'species': 'object',
        'acceptedScientificName': 'object',
        'verbatimScientificName': 'object',
        'typifiedName': 'object',
        'protocol': 'object',
        'lastParsed': 'object',
        'lastCrawled': 'object',
        'repatriated': 'object',
        'relativeOrganismQuantity': 'object',
        'projectId': 'object',
        'isSequenced': 'object',
        'gbifRegion': 'object',
        'publishedByGbifRegion': 'object',
        'level0Gid': 'object',
        'level0Name': 'object',
        'level1Gid': 'object',
        'level1Name': 'object',
        'level2Gid': 'object',
        'level2Name': 'object',
        'level3Gid': 'object',
        'level3Name': 'object',
        'iucnRedListCategory': 'object'
    }
