# Dataset Metadata Template
# 20250102
package_id: # Name of the downloaded archive (0000214-250121130708018)
title: # Full title was written in the xml file under dataset in the package directory
institution_code: # ex: usnm
record_count: # can be found on the webpage linked with the doi
download_date: # yyyy-mm-dd
filter_parameter: # For filtered results, enter the filter parameter here
filter_value: # For filtered results, enter the value that corresponds to the filter paramter
doi: # Found in the xml file under dataset in the package directory