# Dataset Metadata Template
# 20250102
package_id: 0000571-250121130708018 # Name of the downloaded archive (0000214-250121130708018)
title: 'CUMV Amphibian and Reptile Collection' # Full title was written in the xml file under dataset in the package directory
institution_code: cumv # ex: usnm
record_count: 26789 # can be found on the webpage linked with the doi
download_date: 2024-01-21 # yyyy-mm-dd
filter_parameter: # For filtered results, enter the filter parameter here
filter_value: # For filtered results, enter the value that corresponds to the filter paramter
doi: https://doi.org/10.15468/emivh3 # Found in the xml file under dataset in the package directory